### ISSUE TITLE
Errors upon quitting

### ISSUE THREAD

**Issue by morpheusbeing** [Ralith/nachat#1]
1469766663578	addons.productaddons	ERROR	Request failed certificate checks: [Exception... "SSL is required and URI scheme is not https."  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: resource://gre/modules/CertUtils.jsm :: checkCert :: line 145"  data: no]

**Comment by Ralith** [comment]
Where did you see this message? How can it be reproduced?

It looks a lot like something from your web browser rather than the client, to be honest.
