### ISSUE TITLE
Fails to compile with missing <span.h>

### ISSUE THREAD

**Issue by jaakristioja** [Ralith/nachat#8]
Fails to compile with missing `<span.h>`. Dunno what package I have to install for this.

**Comment by jaakristioja** [comment]
There was no warning from running `cmake`. The `make` run failed. I forgot to run the ugly git submodule commands. I'm leaving this open so you can fix the `CMakeLists.txt` to include a warning for this.

**Comment by Ralith** [comment]
I have no plans to make the build system warn you for improperly cloning the repository. If that functionality is important to you, I may consider a pull request for it.
